language: ruby
cache: bundler
services:
  - postgresql
  - redis-server
  - xvfb
sudo: false
addons:
  chrome: stable
  artifacts:
    paths:
      - $(ls -d -1 $PWD/tmp/capybara/* | tr "\n" ":")
env:
  - "DB=postgresql"
before_install:
  - nvm install 12.14.1
install:
  - bundle install
  - npm install
  - npm install --global yarn
  - yarn install
before_script:
  - "cp config/database.yml-example config/database.yml"
  - "cp .env-example .env"
  - "export DISPLAY=:99.0"
  - "bundle exec rake --trace db:setup"
rvm:
  - 2.7.0
script:
  - "bundle exec rspec"
